<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Scrap Location_scrap_location_id_0</name>
   <tag></tag>
   <elementGuidId>c5bbede6-0261-450b-b72a-987b8177b3ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scrap_location_id_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='scrap_location_id_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Scrap Location&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10b87e1c-fd43-46af-95b2-51a3deba5219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eab6f264-8375-4b06-a9cc-f588dc61f034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-autocomplete--input o_input</value>
      <webElementGuid>6213f6bb-6ee1-4abf-ab88-19566a02595e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bdf4ca09-be0c-4bbb-9270-43132805083a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scrap_location_id_0</value>
      <webElementGuid>b1bdcbc1-cf99-495e-95b8-bb3170b1f983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrap_location_id_0&quot;)</value>
      <webElementGuid>cbe4364d-4f5c-49b8-8e7f-89d0d5732fa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='scrap_location_id_0']</value>
      <webElementGuid>5609ba81-0c72-4576-bcfc-d6afadf43a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>4ad56eed-6a95-417e-b5c5-cd5c8e3facff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'scrap_location_id_0']</value>
      <webElementGuid>7b84e7dc-6348-4f2d-946c-569f165028ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
